ToDoList/ToDoList/Models/ToDoItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ToDoList.Models
{
    public class ToDoItem
    {
        public bool done { get; set; }
        public DateTime date { get; set; }
        public string name { get; set; }
        public string details { get; set; }

        public ToDoItem()
        {
            done = false;
            date = DateTime.Now;
            name = "";
            details = "";
        }

        public ToDoItem(bool done, DateTime date, string name, string details)
        {
            this.done = done;
            this.date = date;
            this.name = name;
            this.details = details;
        }
    }
}

ToDoList/ToDoList/Models/ToDoListRepo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Xml.Linq;
using System.Web;

namespace ToDoList.Models
{
    public class ToDoListRepo
    {
        private List<ToDoItem> Items;
        private XDocument ToDoListData;

        public ToDoListRepo()
        {
            ToDoListData = XDocument.Load(HttpContext.Current.Server.MapPath("~/App_Data/ToDoListData.xml"));
            Items = new List<ToDoItem>();
        }

        public List<ToDoItem> getItems()
        {
            try
            {
                var xitems = ToDoListData.Descendants("item")
                                .Select(i => new ToDoItem((bool)i.Element("done"),(DateTime)i.Element("date"),i.Element("name").Value, i.Element("details").Value));

                Items.AddRange(xitems.ToList());
                return Items;
            }
            catch
            {
                return Items;
            }
        }

        public ToDoItem getItem(string name)
        {
            var xitem = ToDoListData.Descendants("item")
               .Elements("name")
               .Where(x => x.Value == name)
               .Select(x => x.Parent).FirstOrDefault();

            ToDoItem item = new ToDoItem((bool)xitem.Element("done"), (DateTime)xitem.Element("date"), xitem.Element("name").Value, xitem.Element("details").Value);
            return item;
        }

        public void AddItem(ToDoItem item)
        {
            ToDoListData.Root.Add(new XElement("item",
                new XElement("done", item.done),
                new XElement("date", item.date),
                new XElement("name", item.name),
                new XElement("details", item.details)
                ));

            ToDoListData.Save(HttpContext.Current.Server.MapPath("~/App_Data/ToDoListData.xml"));
        }

        public void Update(ToDoItem item, string Name)
        {
            var xitem = ToDoListData.Descendants("item")
           .Elements("name")
           .Where(x => x.Value == Name)
           .Select(x => x.Parent).FirstOrDefault();

            xitem.SetElementValue("done", item.done);
            xitem.SetElementValue("date", item.date);
            xitem.SetElementValue("name", item.name);
            xitem.SetElementValue("details", item.details);
            ToDoListData.Save(HttpContext.Current.Server.MapPath("~/App_Data/ToDoListData.xml"));
        }

        public void Delete(ToDoItem item)
        {
            ToDoListData.Descendants("item")
               .Elements("name")
               .Where(x => x.Value == item.name)
               .Select(x => x.Parent)
               .Remove();

            ToDoListData.Save(HttpContext.Current.Server.MapPath("~/App_Data/ToDoListData.xml"));
        }

        public void CheckBox(string name, bool isChecked)
        {
            ToDoItem item = getItem(name);
            item.done = isChecked;
            Update(item, item.name);
        }
 
    }
}

ToDoList/ToDoList/Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ToDoList.Models;

namespace ToDoList.Controllers
{
    public class MainController : Controller
    {
        ToDoListRepo _ToDoListRepo = new ToDoListRepo();

        public ActionResult Index()
        {
            return View(_ToDoListRepo.getItems());
        }

        [HttpGet]
        public ActionResult AddItem()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddItem(ToDoItem item)
        {
            _ToDoListRepo.AddItem(item);
            return RedirectToAction("../Main/Index");
        }

        [HttpGet]                                     
        public ActionResult Delete(string name)
        {
            return View(_ToDoListRepo.getItem(name));
        }

        [HttpPost]                                      //[HttpPost, ActionName("Delete")]
        public ActionResult Delete(ToDoItem item)
        {
            _ToDoListRepo.Delete(item);
            return RedirectToAction("../Main/Index");
        }

        [HttpGet]
        public ActionResult Update(string name)
        {
            TempData["oldName"] = name;
            return View(_ToDoListRepo.getItem(name));
        }

        [HttpPost]                                      
        public ActionResult Update(ToDoItem item)
        {           
            _ToDoListRepo.Update(item,TempData["oldName"].ToString());
            return RedirectToAction("../Main/Index");
        }

        [HttpGet]
        public ActionResult Info(string name)
        {
            return View(_ToDoListRepo.getItem(name));
        }

        [HttpPost]
        public ActionResult CheckBox(string name, string isChecked)
        {
            _ToDoListRepo.CheckBox(name, isChecked == "true");
            return RedirectToAction("../Main/Index");
        }

    }
}

ToDoList/ToDoList/Views/Main/AddItem.cshtml
@{
    ViewBag.Title = "AddItem";
}

<h2>Add an Item:</h2>

@using (Html.BeginForm("AddItem", "Main", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <p>
        <div class="input-group">
            <span class="input-group-addon" id="basic-addon1">Date</span>
            <input name="date" type="text" id="datepicker" class="form-control" placeholder="Due Date" aria-label="Due Date" aria-describedby="basic-addon1" required>
        </div>
        <div class="input-group">
            <span class="input-group-addon" id="basic-addon2">Name</span>
            <input name="name" type="text" id="itemname" class="form-control" placeholder="Item Name" aria-label="Item Name" aria-describedby="basic-addon2" required>
        </div>
        <div class="input-group">
            <span class="input-group-addon" id="basic-addon3">Details</span>
            <textarea name="details" type="text" id="itemdetails" class="form-control" rows="3" placeholder="Item Details" aria-label="Item Details" aria-describedby="basic-addon3" required></textarea>
        </div>
    </p>

    <p>
        <input id="additem" type="submit" value="AddItem"/>
    </p>
}

ToDoList/ToDoList/Views/Main/Delete.cshtml
@model ToDoList.Models.ToDoItem

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>
<h3>@Model.name</h3>
<h5>Are you sure?</h5>
<br />

@using (Html.BeginForm("Delete", "Main", FormMethod.Post, new { id = "delForm" }))
{
    @Html.HiddenFor(m => m.name)
    <input type="submit" value="Delete" />
}

ToDoList/ToDoList/Views/Main/Index.cshtml
@using ToDoList.Models

@{
    ViewBag.Title = "Index";
}

<h2>ToDoList Items:</h2>

<p>
    <table class="table table-hover" id="ToDoTable">
        <thead>
            <tr>
                <th scope="col" onclick="sortTable(0, 'checkbox')">Done</th>
                <th scope="col" onclick="sortTable(1, 'date')">Due Date</th>
                <th scope="col" onclick="sortTable(2, 'text')">Item Name</th>
                <th scope="col">Manage</th>
            </tr>
        </thead>
        <tbody>
            @foreach (ToDoItem item in Model)
            {
                <tr>
                    <td class="itemDone">
                        @Html.CheckBoxFor(Model => item.done, new { @class = "checkBox", @data_url = @Url.Action("CheckBox", "Main", new { name = item.name }) })                          
                    </td>
                    <td class="itemDate">@item.date.ToShortDateString()</td>
                    <td class="itemName">@item.name</td>
                    <td>
                        <button class="btn btn-danger btn-sm" onclick="location.href='@Url.Action("Delete", "Main", new { name = item.name })'">
                            <span class="glyphicon glyphicon-trash"></span>
                        </button>
                        <button class="btn btn-warning btn-sm" onclick="location.href='@Url.Action("Update", "Main", new { name = item.name })'">
                            <span class="glyphicon glyphicon-pencil"></span>
                        </button>
                        <button class="btn btn-info btn-sm" onclick="location.href='@Url.Action("Info", "Main", new { name = item.name })'">
                            <span class="glyphicon glyphicon-eye-open"></span>
                        </button>
                    </td>
                </tr>
            }
        </tbody>
    </table>


</p>


@*<input type="checkbox" class="checkBox" data-url='@Url.Action("CheckBox", "Main", new { name = item.name })' />*@
@*@Html.ActionLink("Delete", "Delete", "Main", new { name = item.name }, new { @style = "" })*@
@*@onclick = "return confirm('Are you sure')"*@

ToDoList/ToDoList/Views/Main/Info.cshtml
@{
    ViewBag.Title = "Info";
}

<h2>Item Info</h2>

<p>
    <div class="input-group">
        <span class="input-group-addon" id="basic-addon1">Date</span>
        <input name="date" type="text" class="form-control readonly" value="@Model.date.ToShortDateString()" aria-label="Due Date" aria-describedby="basic-addon1" readonly>
    </div>
    <div class="input-group">
        <span class="input-group-addon" id="basic-addon2">Name</span>
        <input name="name" type="text" id="itemname" class="form-control readonly" value="@Model.name" aria-label="Item Name" aria-describedby="basic-addon2" readonly>
    </div>
    <div class="input-group">
        <span class="input-group-addon" id="basic-addon3">Details</span>
        <textarea name="details" type="text" id="itemdetails" class="form-control readonly" rows="3" aria-label="Item Details" aria-describedby="basic-addon3" readonly>@Model.details</textarea>
    </div></p>

ToDoList/ToDoList/Views/Main/Update.cshtml
@{
    ViewBag.Title = "Update";
}

<h2>Update Item:</h2>

@using (Html.BeginForm("Update", "Main", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <p>
        <input type="hidden" name="done" value="@Model.done.ToString()" class="form-control" />
        <div class="input-group">
            <span class="input-group-addon" id="basic-addon1">Date</span>
            <input name="date" type="text" id="datepicker" class="form-control" value="@Model.date.ToShortDateString()" aria-label="Due Date" aria-describedby="basic-addon1" required>
        </div>
        <div class="input-group">
            <span class="input-group-addon" id="basic-addon2">Name</span>
            <input name="name" type="text" id="itemname" class="form-control" value="@Model.name" aria-label="Item Name" aria-describedby="basic-addon2" required>
        </div>
        <div class="input-group">
            <span class="input-group-addon" id="basic-addon3">Details</span>
            <textarea name="details" type="text" id="itemdetails" class="form-control" rows="3" aria-label="Item Details" aria-describedby="basic-addon3" required>@Model.details</textarea>
        </div>
    </p>

    <p>
        <input id="updateitem" type="submit" value="UpdateItem" />
    </p>
}

ToDoList/ToDoList/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ToDoList</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/jquery-ui.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/main.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ToDoList", "Index", "Main", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @Html.ActionLink("AddItem", "AddItem", "Main", new { area = "" }, new { @class = "navbar-brand" })
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p></p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.2.1.min.js"></script>
    <script src="~/Scripts/jquery-ui.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/main.js"></script>
</body>
</html>